MarkerSetName: "Offline Players"

#Whether to use BlueMap's own player icons, instead of downloading manually
UseBlueMapSource: true

#The place to get the playerhead icons from. Leave empty to use BlueMap's own files
#Accepted variables: {UUID}, {USERNAME}
# Examples:
#  SkinURL: ""
#  SkinURL: "https://crafatar.com/avatars/{UUID}.png?size=8&overlay=true"
SkinURL: "https://crafatar.com/avatars/{UUID}.png?size=8&overlay=true"

VerboseErrors: false