name: BlueMapOfflinePlayerMarkers
version: ${project.version}
main: com.technicjelle.bluemapofflineplayermarkers.Main
api-version: 1.13
depend:
  - BlueMap
authors:
  - TechnicJelle
  - Mark-255
  - Seercat3160
description: Adds markers where players have logged off to BlueMap
website: https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers
