# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Set up JDK 11
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/BlueMapOfflinePlayerMarkers/BlueMapOfflinePlayerMarkers/target/*
